Added Generalized PoW for CPU
iotaledger-archive/iota.legacy.rs pull request #67
Opened 2017-07-06 02:26 UTC by paulhandy

2017-07-06 03:51 UTC, th0br0 requested changes

2017-07-06 03:51 UTC, th0br0 commented on curl-cpu/src/search.rs
> +    fn offset(&mut self);
Could you document this?

2017-07-06 03:51 UTC, th0br0 commented on curl-cpu/src/search.rs
> +        self[0].0 = 0b1101101101101101101101101101101101101101101101101101101101101101;
We probably want to explain how we end up at these magic numbers

2017-07-06 03:51 UTC, th0br0 commented on curl-cpu/src/search.rs
> +pub fn prepare_search(input: &[BCTrit]) -> Vec<BCTrit> {
documentation

2017-07-06 03:51 UTC, th0br0 commented on curl-cpu/src/search.rs
> +    //use alloc::Vec;
unused

2017-07-06 03:51 UTC, th0br0 commented on curl-cpu/src/search.rs
> +mod cpu_search {
my idea was to move this code to, e.g. `src/par/search.rs`  - just do a typedef somewhere in `lib.rs` e.g. at the level of the `pub use` at the end of this file?
I don't think that this is the only part of this crate that we want to parallelise?

2017-07-06 03:51 UTC, th0br0 commented on tmath/src/increment.rs
> +    fn incr(&mut self) -> usize;
document the return value?

2017-07-06 03:51 UTC, th0br0 commented on curl/src/tests.rs
> +        let final_t: Trinary = trans_copy.trits()[..(trans_copy.len_trits() - HASH_LENGTH)]
As the hashing logic in here is rather fundamental, maybe we should use that to a `trait TrinaryHash` and implement for all `IntoTrinary`?

2017-07-06 16:36 UTC, paulhandy commented on curl-cpu/src/search.rs
> +        self[0].0 = 0b1101101101101101101101101101101101101101101101101101101101101101;
I think it should really just be generated automagically for different word sizes.

2017-07-06 16:38 UTC, th0br0 commented
Sounds good. Could you file an issue? I'm happy with leaving it as is, just
don't want to lose track.

On 6 Jul 2017 19:36, "Paul Handy" <notifications@github.com> wrote:

> *@paulhandy* commented on this pull request.
> ------------------------------
>
> In curl-cpu/src/search.rs
> <https://github.com/iotaledger/iota.rs/pull/67#discussion_r125951605>:
>
> > @@ -0,0 +1,124 @@
> +
> +use trytes::*;
> +use alloc::Vec;
> +use curl::*;
> +use cpucurl::*;
> +use core::cmp::min;
> +
> +trait Offset {
> +    fn offset(&mut self);
> +}
> +
> +impl<'a> Offset for &'a mut [BCTrit] {
> +    fn offset(&mut self) {
> +        self[0].0 = 0b1101101101101101101101101101101101101101101101101101101101101101;
>
> I think it should really just be generated automagically for different
> word sizes.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/iotaledger/iota.rs/pull/67#discussion_r125951605>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAB5FHtHgIZXVssOH6tLihwm6rJ4pyQSks5sLQ0GgaJpZM4OPFd4>
> .
>

2017-07-06 16:57 UTC, paulhandy commented on curl-cpu/src/search.rs
> +mod cpu_search {
This is the only part of the crate that we need to parallelize.

2017-07-07 04:40 UTC, th0br0 approved these changes
Could you fix the nits and merge then?

2017-07-07 04:40 UTC, th0br0 commented on curl-cpu/src/search.rs
> +        self[0].0 = 0b1101101101101101101101101101101101101101101101101101101101101101;
filed #70

2017-07-07 04:40 UTC, th0br0 commented on curl-cpu/src/search.rs
> +        // TODO: replace with calculated number of threads
Filed #71 could you remove the comment?

2017-07-07 04:40 UTC, th0br0 commented on curl-cpu/src/search.rs
> +        let running = Arc::new(AtomicBool::new(true));
Does this need to be wrapped up in an `Arc`? Acces

2017-07-07 05:10 UTC, paulhandy commented
merged

2017-07-07 05:10 UTC, closed without merging